package main

import (
	"fmt"
	"strings"
)

// Generates the character definition files around the converted animations.
//
// Reactive states (being hit, falling, guarding, dizzy) are left to Ikemen's
// common states. What is written here is the part Samurai Shodown does
// differently from a stock MUGEN character:
//
//   - four attack buttons rather than six, with the heavy slash also on both
//     light slash buttons at once
//   - a POW gauge that fills from damage taken instead of damage dealt
//   - a disarmed state that swaps in the weaponless animation set and cuts
//     damage until the sword is picked back up

// Buttons, in MUGEN terms: x/y/z are punches (here, slashes) and a/b/c kicks.
// The two families mirror each other: light, medium, and a heavy that also
// comes out of the two lighter buttons pressed together.
const (
	btnLightSlash  = "x"
	btnMediumSlash = "y"
	btnHeavySlash  = "z"
	btnLightKick   = "a"
	btnMediumKick  = "b"
	btnHeavyKick   = "c"
	btnRearm       = "d"
)

// varDisarmed is set to 1 once the sword has been knocked away.
const varDisarmed = 0

// powRageStart is where the gauge counts as full, on Ikemen's 0..3000 scale.
const powRageStart = 2500

type AttackSpec struct {
	State   int32
	Anim    int32
	Name    string
	Type    string // S, C or A
	Damage  int
	HitElem int    // 1-based AnimElem that first has an attack box
	Height  string // High or Low
	Command string
	// DisarmedAnim is the weaponless animation, when the source ships one.
	DisarmedAnim int32
	HasDisarmed  bool
	// IsSlash marks weapon attacks, which lose most of their damage once the
	// sword is gone.
	IsSlash bool
}

// attackStates lists the normals we wire up, in MUGEN's conventional numbering.
var attackStates = []struct {
	state, anim int32
	name, kind  string
	height      string
	button      string
	slash       bool
}{
	{200, 200, "punch", "S", "High", btnLightSlash, true},
	{210, 210, "midpunch", "S", "High", btnMediumSlash, true},
	{230, 230, "strongpunch", "S", "High", btnHeavySlash, true},
	{240, 240, "kick", "S", "High", btnLightKick, false},
	{250, 250, "midkick", "S", "High", btnMediumKick, false},
	{260, 260, "strongkick", "S", "High", btnHeavyKick, false},
	{400, 400, "crouchPunch", "C", "Low", btnLightSlash, true},
	{410, 410, "crouchmidPunch", "C", "Low", btnMediumSlash, true},
	{430, 430, "crouchstrongPunch", "C", "Low", btnHeavySlash, true},
	{440, 440, "crouchKick", "C", "Low", btnLightKick, false},
	{450, 450, "crouchmidKick", "C", "Low", btnMediumKick, false},
	{460, 460, "crouchstrongKick", "C", "Low", btnHeavyKick, false},
	{600, 600, "jumpPunch", "A", "High", btnLightSlash, true},
	{610, 610, "jumpmidPunch", "A", "High", btnMediumSlash, true},
	{630, 630, "jumpstrongPunch", "A", "High", btnHeavySlash, true},
	{640, 640, "jumpKick", "A", "High", btnLightKick, false},
	{650, 650, "jumpmidKick", "A", "High", btnMediumKick, false},
	{660, 660, "jumpstrongKick", "A", "High", btnHeavyKick, false},
}

func BuildAttacks(src *Source) []AttackSpec {
	var out []AttackSpec
	for _, a := range attackStates {
		anim := src.Anim(a.name)
		if anim == nil {
			continue
		}
		hitElem := 0
		for i, f := range anim.Frames {
			if len(f.Attack) > 0 {
				hitElem = i + 1
				break
			}
		}
		if hitElem == 0 {
			// No active frame means the table has no attack box; skip rather
			// than emit a move that can never connect.
			continue
		}
		// Unlike the collision boxes, damage is animation-scoped in the source:
		// every PushBack overwrites it, so the last call is what the original
		// engine actually used. Reading it per frame would pick up values that
		// were only ever dead data, such as the punch's stray 212.
		damage := anim.Frames[len(anim.Frames)-1].Damage
		if damage <= 0 || damage > 120 {
			damage = 10
		}
		spec := AttackSpec{
			State: a.state, Anim: a.anim, Name: a.name, Type: a.kind,
			Damage: damage, HitElem: hitElem, Height: a.height,
			Command: a.button, IsSlash: a.slash,
		}
		spec.DisarmedAnim, spec.HasDisarmed = DisarmedFor(src, a.anim)
		out = append(out, spec)
	}
	return out
}

func WriteDef(charName, fileBase string) string {
	return fmt.Sprintf(`; %s - generated by SamuraiTools/chargen.
[Info]
name = "%s"
displayname = "%s"
versiondate = 01,01,2026
mugenversion = 1.1
author = "converted from X-Mat Studio data"
localcoord = 320, 240

[Files]
cmd = %s.cmd
cns = %s.cns
; The same file serves as both constants and states; without an st entry the
; compiler never reads the state definitions at all.
st = %s.cns
sprite = %s.sff
anim = %s.air
stcommon = common1.cns

[Arcade]
intro.storyboard =
ending.storyboard =
`, charName, charName, charName, fileBase, fileBase, fileBase, fileBase, fileBase)
}

func WriteCns(src *Source, attacks []AttackSpec, specials []SpecialSpec) string {
	var b strings.Builder

	b.WriteString(`; Generated by SamuraiTools/chargen. Regenerate rather than edit.

[Data]
life = 1000
power = 3000
attack = 100
defence = 100
fall.defence_up = 50
liedown.time = 60
airjuggle = 15
sparkno = 2
guard.sparkno = 40
KO.echo = 0
volume = 0
IntPersistIndex = 60
FloatPersistIndex = 40

[Size]
xscale = 1
yscale = 1
ground.back = 15
ground.front = 16
air.back = 12
air.front = 12
height = 60
attack.dist = 160
proj.attack.dist = 90
proj.doscale = 0
head.pos = -5, -90
mid.pos = -5, -60
shadowoffset = 0
draw.offset = 0, 0

[Velocity]
walk.fwd = 2.4
walk.back = -2.2
run.fwd = 4.6, 0
run.back = -4.5, -3.8
jump.neu = 0, -8.4
jump.back = -2.55
jump.fwd = 2.5
runjump.back = -2.55, -8.1
runjump.fwd = 4, -8.1
airjump.neu = 0, -8.1
airjump.back = -2.55
airjump.fwd = 2.5

[Movement]
airjump.num = 0
airjump.height = 35
yaccel = .44
stand.friction = .85
crouch.friction = .82

`)

	writeAlwaysState(&b, attacks)
	writeRearmState(&b, src)

	// States 0/10/11/12/20/40/50/52 are deliberately absent. Ikemen already
	// ships correct versions in data/common1.cns.zss, and the engine itself
	// drives the transitions between them (char.go, "Perform basic actions"),
	// but only while ctrl is set. Redefining them here overrode the working
	// versions with ones that never set walk velocity and cleared ctrl on
	// crouch, which left the character unable to walk or stand back up.

	writeDisarmedSwaps(&b, src)

	b.WriteString("; ----------------------------------------------------------------------------\n")
	b.WriteString("; Attacks\n\n")
	for _, a := range attacks {
		writeAttackState(&b, a)
	}
	writeSpecialStates(&b, specials)
	return b.String()
}

// writeAlwaysState emits Statedef -2, which runs every frame whatever the
// character is doing, and carries the systems that are not tied to one move.
func writeAlwaysState(b *strings.Builder, attacks []AttackSpec) {
	// A weapon is knocked loose by heavy blows, so the roll only happens on
	// hits at least as strong as the heaviest slash this character owns.
	threshold := 0
	for _, a := range attacks {
		if a.IsSlash && a.Damage > threshold {
			threshold = a.Damage
		}
	}
	if threshold <= 0 {
		threshold = 20
	}

	fmt.Fprintf(b, `; ----------------------------------------------------------------------------
; Always-on systems: rage, weapon loss

[Statedef -2]

; Damage is situational rather than fixed: a full POW gauge is the series' rage
; state, and fighting bare-handed hurts far less.
[State -2, AttackScale]
type = AttackMulSet
trigger1 = 1
value = ifelse(var(%d) = 1, 0.55, ifelse(Power >= %d, 1.3, 1.0))

; Decided once, on the frame the hit lands, so the roll cannot repeat for every
; frame of the same hitstun.
[State -2, Disarm]
type = VarSet
triggerall = var(%d) = 0
triggerall = MoveType = H
triggerall = Time = 0
triggerall = GetHitVar(damage) >= %d
trigger1 = Random < 300
var(%d) = 1

`, varDisarmed, powRageStart, varDisarmed, threshold, varDisarmed)
}

// writeRearmState lets the sword be recovered; without it the round would stay
// bare-handed once disarmed.
func writeRearmState(b *strings.Builder, src *Source) {
	var anim int32 = 0
	if a := src.Anim("pickUpSword"); a != nil && len(a.Frames) > 0 {
		anim = actionMap["pickUpSword"]
	}
	fmt.Fprintf(b, `; ----------------------------------------------------------------------------
; Sword recovery

[Statedef 1500]
type = S
movetype = I
physics = S
anim = %d
ctrl = 0
velset = 0, 0

[State 1500, Rearm]
type = VarSet
trigger1 = AnimTime = 0
var(%d) = 0

[State 1500, End]
type = ChangeState
trigger1 = AnimTime = 0
value = 0
ctrl = 1

`, anim, varDisarmed)
}

// writeDisarmedSwaps redirects the shared movement states onto the weaponless
// animations, for the ones the source actually ships.
func writeDisarmedSwaps(b *strings.Builder, src *Source) {
	b.WriteString("; ----------------------------------------------------------------------------\n")
	b.WriteString("; Weaponless movement animations\n\n[Statedef -3]\n\n")

	for _, m := range []struct {
		base  int32
		state string
	}{
		{0, "stand"},
		{11, "crouch"},
		{20, "walkfwd"},
		{21, "walkback"},
		{50, "jump"},
	} {
		dis, ok := DisarmedFor(src, m.base)
		if !ok {
			continue
		}
		fmt.Fprintf(b, `[State -3, %s]
type = ChangeAnim
triggerall = var(%d) = 1 && MoveType = I
trigger1 = Anim = %d
value = %d

`, m.state, varDisarmed, m.base, dis)
	}
}

func writeAttackState(b *strings.Builder, a AttackSpec) {
	physics := map[string]string{"S": "S", "C": "C", "A": "A"}[a.Type]
	returnState := "0"
	if a.Type == "C" {
		returnState = "11"
	} else if a.Type == "A" {
		returnState = "50"
	}

	fmt.Fprintf(b, "; %s\n[Statedef %d]\n", a.Name, a.State)
	fmt.Fprintf(b, `type = %s
movetype = A
physics = %s
juggle = 1
velset = 0, 0
ctrl = 0
anim = %d
poweradd = 0
sprpriority = 2

`, a.Type, physics, a.Anim)

	if a.HasDisarmed {
		fmt.Fprintf(b, `[State %d, Disarmed]
type = ChangeAnim
trigger1 = Time = 0 && var(%d) = 1
value = %d

`, a.State, varDisarmed, a.DisarmedAnim)
	}

	// POW fills from damage taken, so the attacker is paid nothing and the
	// defender is paid instead. That inverts the usual MUGEN arrangement.
	fmt.Fprintf(b, `[State %d, HitDef]
type = HitDef
trigger1 = AnimElem = %d
attr = %s, NA
damage = %d, 0
animtype = Light
guardflag = MA
hitflag = MAF
pausetime = 6, 6
sparkno = 0
sparkxy = -10, -60
hitsound = 5, 0
guardsound = 6, 0
ground.type = %s
ground.slidetime = 8
ground.hittime = 12
ground.velocity = -4
air.velocity = -2.5, -3.5
getpower = 0, 0
givepower = %d, %d

[State %d, End]
type = ChangeState
trigger1 = AnimTime = 0
value = %s
ctrl = 1

`, a.State, a.HitElem, a.Type, a.Damage, a.Height,
		a.Damage*6, a.Damage*2, a.State, returnState)
}

func WriteCmd(attacks []AttackSpec, specials []SpecialSpec) string {
	var b strings.Builder
	b.WriteString(`; Generated by SamuraiTools/chargen.
;
; Four attack buttons, as in the arcade original. Buttons are named in MUGEN
; terms; the default keyboard layout matches the PC release, with slashes on
; the lower row and kicks on the upper row:
;
;   x        Quick Slash    A      J
;   y        Power Slash    B      K
;   z / x+y  Strong Slash   A+B    L
;   a        Quick Kick     C      U
;   b        Power Kick     D      I
;   c / a+b  Strong Kick    C+D    O
;   ` + btnRearm + `        pick the sword back up   P
;
; Specials, each finishing on the quick slash button:
;
;   D, DF, F + slash              blade wave, throws a shot
;   D, DB, B + slash              sword rush, hits several times
;   D, DF, F, D, DF, F + slash    rage rush, needs a full POW gauge and spends it
;
; These are tested before the normals, so the slash that ends a motion does not
; come out as a plain attack instead.

[Remap]
[Defaults]
command.time = 15
command.buffer.time = 1

`)
	writeSpecialCommands(&b, specials)
	b.WriteString(`[Command]
name = "x"
command = x
[Command]
name = "y"
command = y
[Command]
name = "z"
command = z
[Command]
name = "a"
command = a
[Command]
name = "b"
command = b
[Command]
name = "c"
command = c

; Each heavy also comes out of the two lighter buttons of its family together,
; which is how the arcade original works.
[Command]
name = "a+b"
command = a+b
time = 1

[Command]
name = "x+y"
command = x+y
time = 1

[Command]
name = "rearm"
command = ` + btnRearm + `

[Command]
name = "holddown"
command = /$D
time = 1
[Command]
name = "holdfwd"
command = /$F
time = 1
[Command]
name = "holdback"
command = /$B
time = 1
[Command]
name = "holdup"
command = /$U
time = 1

; Required by Ikemen's common states for air recovery.
[Command]
name = "recovery"
command = x
[Command]
name = "recovery"
command = y
[Command]
name = "recovery"
command = z
[Command]
name = "recovery"
command = a
[Command]
name = "recovery"
command = b

[Statedef -1]

; Sword recovery is tested first: while disarmed it matters more than any normal.
[State -1, rearm]
type = ChangeState
value = 1500
triggerall = command = "rearm"
trigger1 = var(` + fmt.Sprint(varDisarmed) + `) = 1 && StateType != A && Ctrl

`)

	writeSpecialTriggers(&b, specials)

	// Air attacks first: they are only reachable while airborne, so testing them
	// ahead of the ground normals keeps the trigger conditions simple.
	for _, group := range []struct {
		kind      string
		condition string
	}{
		{"A", "StateType = A && Ctrl"},
		{"C", "StateType = C && Ctrl"},
		{"S", "StateType = S && Ctrl"},
	} {
		for _, a := range attacks {
			if a.Type != group.kind {
				continue
			}
			cmd := fmt.Sprintf(`command = "%s"`, a.Command)
			// A heavy is reachable either from its own button or from the two
			// lighter buttons of the same family.
			switch a.Command {
			case btnHeavySlash:
				cmd = fmt.Sprintf(`command = "%s" || command = "%s+%s"`,
					btnHeavySlash, btnLightSlash, btnMediumSlash)
			case btnHeavyKick:
				cmd = fmt.Sprintf(`command = "%s" || command = "%s+%s"`,
					btnHeavyKick, btnLightKick, btnMediumKick)
			}
			fmt.Fprintf(&b, `[State -1, %s]
type = ChangeState
value = %d
triggerall = %s
trigger1 = %s

`, a.Name, a.State, cmd, group.condition)
		}
	}
	return b.String()
}
